# -*- coding: utf-8 -*-
"""Covid_19_Deta_set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHBfa5yBtjZh-n-7g1rVTJzKnXuPpZVY
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

import os
os.listdir()

df = pd.read_csv("archive (2).zip")
df.head()

df.isnull().sum()

df.fillna(0, inplace=True)

# Fix data types properly
df['day'] = pd.to_datetime(df['day'])
df['time'] = pd.to_datetime(df['time'], errors='coerce')

# Ensure numeric columns don't have negative numbers
num_cols = ['Cases', 'Recovered', 'Deaths', 'Tests']
for col in num_cols:
    df[col] = df[col].clip(lower=0)

df.info()
df.describe()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext google.colab.data_table
df

